language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm update
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $portfoliotoken
  local_dir: build
  on:
    branch: master
